In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from pycaret.regression import *

In [ ]:
 final = pd.read_csv('Data/df4.csv')

In [ ]:
final.drop(columns='seller_id', inplace=True)

In [ ]:
final.rename(columns={'Unnamed: 0':'seller'}, inplace=True)

In [ ]:
final.value_counts()

In [ ]:
regression = setup(data = final, remove_outliers=True, unknown_categorical_method='most_frequent', target = 'review_score', session_id=42, imputation_type='iterative', normalize=True)

In [ ]:
best_model = compare_models()
best_model

In [ ]:
evaluate_model(best_model)

In [2]:
final2 = pd.read_csv('Data/df1.csv')

In [3]:
total_vendas = pd.read_csv('Data/df_total_vendas.csv')
total_vendas.drop(columns='Unnamed: 0', inplace=True)

In [4]:
final2 = final2.merge(total_vendas, left_on='seller_id', right_on='seller_id' )

In [12]:
final2.columns

Index(['Unnamed: 0', 'seller_id', 'seller_zip_code_prefix', 'seller_city',
       'seller_state', 'order_id', 'order_item_id', 'product_id', 'price',
       'freight_value', 'customer_id_x', 'order_status_x',
       'order_approved_at_x', 'product_category_name',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm',
       'Unnamed: 0_y', 'customer_id_y', 'order_status_y',
       'order_purchase_timestamp_y', 'order_approved_at_y',
       'order_delivered_carrier_date_y', 'order_delivered_customer_date_y',
       'order_estimated_delivery_date_y', 'review_score',
       'review_creation_date', 'review_answer_timestamp', 'tempo_resposta',
       'prazo_entrega', 'total_vendas'],
      dtype='object')

In [5]:
final2.drop(columns=['seller_id', 'seller_zip_code_prefix', 'seller_city', 'order_id', 'product_id', 'customer_id_x', 'order_approved_at_x', 'Unnamed: 0_y', 'customer_id_y', 'order_purchase_timestamp_y', 'order_approved_at_y', 'order_delivered_carrier_date_y', 'order_delivered_customer_date_y', 'order_estimated_delivery_date_y', 'review_creation_date', 'review_answer_timestamp'], inplace=True)

In [6]:
final2.rename(columns={'Unnamed: 0':'seller'}, inplace=True)

In [7]:
final2.dropna(inplace=True)

In [18]:
final2.to_csv('Data/final2.csv')

In [28]:
final3.to_csv('Data/final3.csv')

In [9]:
final2.columns

Index(['seller', 'seller_state', 'order_item_id', 'price', 'freight_value',
       'order_status_x', 'product_category_name', 'product_description_lenght',
       'product_photos_qty', 'product_weight_g', 'product_length_cm',
       'product_height_cm', 'product_width_cm', 'order_status_y',
       'review_score', 'tempo_resposta', 'prazo_entrega', 'total_vendas'],
      dtype='object')

In [11]:
final3=final2.drop(columns=['product_length_cm', 'product_height_cm', 'product_width_cm', 'product_weight_g', 'order_status_x'])

In [27]:
final3['total_vendas'].value_counts()

2020    2020
1984    1984
1932    1932
1811    1811
1568    1568
        ...
115      111
107      107
97        97
120       91
371        1
Name: total_vendas, Length: 260, dtype: int64

In [30]:
final3

,seller,seller_state,order_item_id,price,freight_value,product_category_name,product_description_lenght,product_photos_qty,order_status_y,review_score,tempo_resposta,prazo_entrega,total_vendas
0,0,SP,1.0,185.0,13.63,esporte_lazer,858.0,1.0,delivered,4,-1.0,15.0,68
1,1,SP,2.0,185.0,13.63,esporte_lazer,858.0,1.0,delivered,4,-1.0,15.0,68
2,3028,SP,1.0,135.0,18.20,esporte_lazer,858.0,1.0,delivered,5,-1.0,6.0,68
3,3029,SP,2.0,135.0,18.20,esporte_lazer,858.0,1.0,delivered,5,-1.0,6.0,68
4,8429,SP,1.0,39.9,12.69,esporte_lazer,2578.0,1.0,delivered,5,-4.0,14.0,68
...,...,...,...,...,...,...,...,...,...,...,...,...,...
112367,112362,SP,1.0,89.9,18.73,moveis_decoracao,1141.0,2.0,delivered,4,-9.0,13.0,1
112368,112470,PR,1.0,289.9,37.35,beleza_saude,696.0,1.0,delivered,5,-1.0,14.0,1
112369,112784,SP,1.0,79.9,18.44,sinalizacao_e_seguranca,609.0,2.0,delivered,5,-2.0,13.0,1
112370,112790,SP,1.0,750.0,17.69,relogios_presentes,381.0,4.0,delivered,1,-2.0,6.0,1
112371,113114,PR,1.0,161.0,40.34,moveis_cozinha_area_de_servico_jantar_e_jardim,245.0,1.0,delivered,5,-2.0,23.0,1

In [32]:
regression2 = setup(data = final3, remove_outliers=True, unknown_categorical_method='most_frequent', target = 'total_vendas', session_id=42, imputation_type='iterative', normalize=True, n_jobs=-3, numeric_features=['review_score', 'prazo_entrega', 'tempo_resposta', 'product_photos_qty', 'product_description_lenght', 'freight_value', 'price', 'order_item_id'], ignore_features=['seller'])

In [33]:
best_model2 = compare_models()

In [34]:
evaluate_model(best_model2)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Hyperparameters', 'param…

In [38]:
predict_model(best_model2)

,order_item_id,price,freight_value,product_description_lenght,product_photos_qty,review_score,tempo_resposta,prazo_entrega,seller_state_BA,seller_state_DF,...,product_category_name_relogios_presentes,product_category_name_telefonia,product_category_name_utilidades_domesticas,order_status_y_canceled,order_status_y_delivered,order_status_y_invoiced,order_status_y_processing,order_status_y_shipped,total_vendas,Label
0,-0.284445,1.798874,2.019063,1.133441,1.042105,0.697983,-0.346822,1.011202,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,11,76.22
1,-0.284445,0.718493,0.079767,-0.099975,2.786920,0.697983,-0.042650,0.613553,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,100,245.79
2,-0.284445,-0.098592,-0.126002,-0.185778,2.786920,0.697983,0.058740,2.601801,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,99,60.10
3,-0.284445,-0.576917,-0.571730,-0.593342,-0.702710,0.697983,0.160131,1.309440,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,163,161.89
4,-0.284445,0.979278,-0.642641,4.669746,2.786920,0.697983,-0.042650,-0.082334,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,747,720.47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33227,-0.284445,0.308148,4.852347,-0.239405,-0.702710,-0.022533,0.160131,1.806502,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1367,1279.69
33228,-0.284445,-0.402187,-0.098778,-0.758819,0.460500,0.697983,0.160131,-0.579396,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,219,304.39
33229,-0.284445,-0.123710,0.470412,-0.608664,2.786920,-0.022533,0.160131,-0.380571,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,137,138.16
33230,-0.284445,-0.003582,-0.066488,-0.239405,-0.121105,0.697983,-0.042650,2.601801,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1148,1119.16
33231,-0.284445,0.537537,-0.733813,-0.237873,-0.702710,0.697983,0.160131,-0.281159,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,60,506.32

In [40]:
final3['total_vendas'].mean()

431.3428633331227