In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from pycaret.regression import *

In [35]:
 final = pd.read_csv('Data/df4.csv')

In [36]:
final.drop(columns='seller_id', inplace=True)

In [37]:
final.rename(columns={'Unnamed: 0':'seller'}, inplace=True)

In [56]:
final.value_counts()

seller  total_vendas  review_score  antecipacao_entrega
0       2020          5.0            11.0                  1
2028    4             5.0            0.0                   1
2054    3             5.0            12.0                  1
2055    3             5.0            14.0                  1
2056    3             1.0           -1.0                   1
                                                          ..
1032    15            5.0            15.0                  1
1033    15            5.0            11.0                  1
1034    15            2.0            0.0                   1
1035    15            4.0            8.0                   1
3089    1             5.0            23.0                  1
Length: 3090, dtype: int64

In [49]:
regression = setup(data = final, remove_outliers=True, unknown_categorical_method='most_frequent', target = 'review_score', session_id=42, imputation_type='iterative', normalize=True)

In [50]:
best_model = compare_models()
best_model

GradientBoostingRegressor(alpha=0.9, ccp_alpha=0.0, criterion='friedman_mse',
                          init=None, learning_rate=0.1, loss='ls', max_depth=3,
                          max_features=None, max_leaf_nodes=None,
                          min_impurity_decrease=0.0, min_impurity_split=None,
                          min_samples_leaf=1, min_samples_split=2,
                          min_weight_fraction_leaf=0.0, n_estimators=100,
                          n_iter_no_change=None, presort='deprecated',
                          random_state=42, subsample=1.0, tol=0.0001,
                          validation_fraction=0.1, verbose=0, warm_start=False)

In [51]:
evaluate_model(best_model)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Hyperparameters', 'param…

     total_vendas  antecipacao_entrega  review_score     Label
0       -0.288408             0.537292           3.0  4.353612
1       -0.207752             0.659498           5.0  4.503386
2       -0.240014             0.781704           5.0  4.518201
3       -0.288408            -0.806970           5.0  4.198730
4       -0.264211            -1.601307           4.5  2.030212
..            ...                  ...           ...       ...
923     -0.151292             0.231778           5.0  4.682961
924     -0.167424             0.109572           5.0  4.672835
925      0.453631             1.026115           5.0  4.643897
926     -0.223883            -0.562559           1.0  4.439811
927     -0.280342             0.659498           4.0  4.328529

[928 rows x 4 columns]

In [12]:
final2 = pd.read_csv('Data/df1.csv')

In [23]:
final2

,seller,seller_city,seller_state,order_item_id,price,freight_value,order_status_x,product_category_name,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,review_score,tempo_resposta,prazo_entrega
0,0,sao joaquim da barra,SP,1.0,185.00,13.63,delivered,esporte_lazer,858.0,1.0,1300.0,30.0,30.0,35.0,4,-1.0,15.0
1,1,sao joaquim da barra,SP,2.0,185.00,13.63,delivered,esporte_lazer,858.0,1.0,1300.0,30.0,30.0,35.0,4,-1.0,15.0
2,2,sao jose dos campos,SP,1.0,79.79,8.30,delivered,informatica_acessorios,493.0,1.0,245.0,19.0,14.0,14.0,5,-2.0,4.0
3,3,ilicinea,MG,1.0,149.00,45.12,delivered,informatica_acessorios,1893.0,1.0,6550.0,20.0,20.0,20.0,5,-2.0,20.0
4,4,ilicinea,MG,1.0,179.99,42.85,delivered,ferramentas_jardim,2188.0,2.0,7650.0,20.0,20.0,20.0,5,-1.0,19.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113126,113126,santo andre,SP,1.0,226.77,61.20,delivered,moveis_decoracao,623.0,1.0,7250.0,100.0,25.0,25.0,5,-8.0,13.0
113127,113127,rio de janeiro,RJ,1.0,199.99,9.77,delivered,brinquedos,465.0,1.0,2363.0,23.0,27.0,19.0,5,-3.0,11.0
113128,113128,betim,MG,1.0,215.97,15.59,delivered,papelaria,283.0,3.0,4100.0,40.0,37.0,29.0,5,-2.0,15.0
113129,113129,sao bernardo do campo,SP,1.0,50.95,15.46,delivered,esporte_lazer,998.0,5.0,600.0,16.0,10.0,11.0,4,-2.0,15.0
113130,113130,sao paulo,SP,1.0,32.90,7.78,delivered,informatica_acessorios,482.0,2.0,500.0,35.0,5.0,15.0,1,-1.0,9.0

In [14]:
final2.drop(columns=['order_id', 'seller_id', 'customer_id_x', 'product_id', 'order_purchase_timestamp_y', 'order_approved_at_y', 'order_delivered_carrier_date_y', 'order_delivered_customer_date_y', 'order_estimated_delivery_date_y', 'review_creation_date' ,'review_answer_timestamp'], inplace=True)

In [16]:
final2.drop(columns=['order_approved_at_x', 'Unnamed: 0_y', 'customer_id_y', 'seller_zip_code_prefix' ], inplace=True)

In [19]:
final2.drop(columns='order_status_y', inplace=True)

In [21]:
final2.rename(columns={'Unnamed: 0':'seller'}, inplace=True)

In [22]:
final2.dropna(inplace=True)

In [24]:
regression2 = setup(data = final2, remove_outliers=True, unknown_categorical_method='most_frequent', target = 'review_score', session_id=42, imputation_type='iterative', normalize=True, n_jobs=-3)

In [ ]:
best_model2 = compare_models()

IntProgress(value=0, description='Processing: ', max=94)

Initiated  . . . . . . . . . . . . . . . . . .          20:47:10
Status     . . . . . . . . . . . . . . . . . .  Fitting 10 Folds
Estimator  . . . . . . . . . . . . . . . . . .  Lasso Regression