In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from pycaret.regression import *

In [5]:
final = pd.read_csv('Data/df4.csv')
final.head()

,Unnamed: 0,seller_id,total_vendas,review_score,antecipacao_entrega
0,0,6560211a19b47992c3666cc44a7e94c0,2020,5.0,11.0
1,1,4a3ca9315b744ce9f8e9374361493884,1984,4.0,10.0
2,2,1f50f920176fa81dab994f9023523100,1932,5.0,11.0
3,3,cc419e0650a3c5ba77189a1882b7556a,1811,5.0,12.0
4,4,da8622b14eb17ae2831f4ac5b9dab84a,1568,5.0,11.0

In [ ]:
final.drop(columns='seller_id', inplace=True)

In [ ]:
final.rename(columns={'Unnamed: 0':'seller'}, inplace=True)

In [ ]:
final.value_counts()

In [ ]:
regression = setup(data = final, remove_outliers=True, unknown_categorical_method='most_frequent', target = 'review_score', session_id=42, imputation_type='iterative', normalize=True)

In [ ]:
best_model = compare_models()
best_model

In [ ]:
evaluate_model(best_model)

In [6]:
final2 = pd.read_csv('Data/df1.csv')

In [10]:
final2.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'seller_id', 'seller_zip_code_prefix',
       'seller_city', 'seller_state', 'order_id', 'order_item_id',
       'product_id', 'price', 'freight_value', 'customer_id_x',
       'order_status_x', 'order_approved_at_x', 'product_category_name',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm',
       'Unnamed: 0_y', 'customer_id_y', 'order_status_y',
       'order_purchase_timestamp_y', 'order_approved_at_y',
       'order_delivered_carrier_date_y', 'order_delivered_customer_date_y',
       'order_estimated_delivery_date_y', 'review_score',
       'review_creation_date', 'review_answer_timestamp', 'tempo_resposta',
       'prazo_entrega'],
      dtype='object')

In [3]:
total_vendas = pd.read_csv('Data/df_total_vendas.csv')
total_vendas.drop(columns='Unnamed: 0', inplace=True)

In [4]:
final2 = final2.merge(total_vendas, left_on='seller_id', right_on='seller_id' )

In [12]:
final2.columns

Index(['Unnamed: 0', 'seller_id', 'seller_zip_code_prefix', 'seller_city',
       'seller_state', 'order_id', 'order_item_id', 'product_id', 'price',
       'freight_value', 'customer_id_x', 'order_status_x',
       'order_approved_at_x', 'product_category_name',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm',
       'Unnamed: 0_y', 'customer_id_y', 'order_status_y',
       'order_purchase_timestamp_y', 'order_approved_at_y',
       'order_delivered_carrier_date_y', 'order_delivered_customer_date_y',
       'order_estimated_delivery_date_y', 'review_score',
       'review_creation_date', 'review_answer_timestamp', 'tempo_resposta',
       'prazo_entrega', 'total_vendas'],
      dtype='object')

In [5]:
final2.drop(columns=['seller_id', 'seller_zip_code_prefix', 'seller_city', 'order_id', 'product_id', 'customer_id_x', 'order_approved_at_x', 'Unnamed: 0_y', 'customer_id_y', 'order_purchase_timestamp_y', 'order_approved_at_y', 'order_delivered_carrier_date_y', 'order_delivered_customer_date_y', 'order_estimated_delivery_date_y', 'review_creation_date', 'review_answer_timestamp'], inplace=True)

In [6]:
final2.rename(columns={'Unnamed: 0':'seller'}, inplace=True)

In [7]:
final2.dropna(inplace=True)

In [18]:
final2.to_csv('Data/final2.csv')

In [28]:
final3.to_csv('Data/final3.csv')

In [9]:
final2.columns

Index(['seller', 'seller_state', 'order_item_id', 'price', 'freight_value',
       'order_status_x', 'product_category_name', 'product_description_lenght',
       'product_photos_qty', 'product_weight_g', 'product_length_cm',
       'product_height_cm', 'product_width_cm', 'order_status_y',
       'review_score', 'tempo_resposta', 'prazo_entrega', 'total_vendas'],
      dtype='object')

In [11]:
final3=final2.drop(columns=['product_length_cm', 'product_height_cm', 'product_width_cm', 'product_weight_g', 'order_status_x'])

In [27]:
final3['total_vendas'].value_counts()

2020    2020
1984    1984
1932    1932
1811    1811
1568    1568
        ...
115      111
107      107
97        97
120       91
371        1
Name: total_vendas, Length: 260, dtype: int64

In [12]:
regression2 = setup(data = final3, remove_outliers=True, unknown_categorical_method='most_frequent', target = 'total_vendas', session_id=42, imputation_type='iterative', normalize=True, n_jobs=-3)

In [13]:
best_model2 = compare_models()

In [14]:
evaluate_model(best_model2)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Hyperparameters', 'param…

In [16]:
final2_rf=finalize_model(best_model2)

In [29]:
predict_model(final2_rf)

,seller,order_item_id,price,freight_value,product_description_lenght,product_photos_qty,tempo_resposta,prazo_entrega,seller_state_BA,seller_state_DF,...,order_status_y_invoiced,order_status_y_processing,order_status_y_shipped,review_score_1,review_score_2,review_score_3,review_score_4,review_score_5,total_vendas,Label
0,-0.183411,-0.284445,1.798874,2.019063,1.133441,1.042105,-0.346822,1.011202,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,11,19.05
1,-0.483061,-0.284445,0.718493,0.079767,-0.099975,2.786920,-0.042650,0.613553,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,100,82.75
2,-1.229428,-0.284445,-0.098592,-0.126002,-0.185778,2.786920,0.058740,2.601801,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,99,86.63
3,-1.127665,-0.284445,-0.576917,-0.571730,-0.593342,-0.702710,0.160131,1.309440,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,163,163.00
4,0.577576,-0.284445,0.979278,-0.642641,4.669746,2.786920,-0.042650,-0.082334,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,747,720.64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33227,-0.572319,-0.284445,0.308148,4.852347,-0.239405,-0.702710,0.160131,1.806502,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1367,1316.12
33228,0.416441,-0.284445,-0.402187,-0.098778,-0.758819,0.460500,0.160131,-0.579396,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,219,205.06
33229,1.701847,-0.284445,-0.123710,0.470412,-0.608664,2.786920,0.160131,-0.380571,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,137,136.94
33230,-0.598557,-0.284445,-0.003582,-0.066488,-0.239405,-0.121105,-0.042650,2.601801,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1148,1069.52
33231,0.809701,-0.284445,0.537537,-0.733813,-0.237873,-0.702710,0.160131,-0.281159,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,60,212.68